spring:
  profiles:
    active:
      - prod
    group:
      local:
        - db-local
      prod:
        - db-prod

    include:
      - db
      - exception
      - security
      - aws

  web:
    resources:
      add-mappings: true


server:
  shutdown: graceful
  port: 8080

decorator:
  datasource:
    p6spy:
      enable-logging: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'




